name: Slack action test pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline_with_slack_integration:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - id: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - id: test
        run: npm run test
      - name: testing id's
        run: echo "lint outcome ${{ steps.lint.outcome }} test outcome ${{ steps.test.outcome }} "
        if: always()
      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,job,took,eventName #commit,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #   if: ${{ steps.lint.outcome == 'success' }} # always() # Pick up events even if the job fails or is canceled.
