name: Testing stuff

on:
  push:
    branches:
      - master
      - dev

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages include skip
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
#        run: echo "$COMMIT_MESSAGES"
#        run: echo "${{ contains(toJson(github.event.commits.*.message)[0], '#skip' }}"
        if: ${{ contains(github.event.head_commit.message, '#skip') }}
        run: echo "contains skip"
      - name: commit messages not include skip
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
#        run: echo "$COMMIT_MESSAGES"
#        run: echo "${{ contains(toJson(github.event.commits.*.message)[0], '#skip' }}"
        if: ${{ !contains(github.event.head_commit.message, '#skip') }}
        run: echo "doesn't contain skip"
